# Generated by Django 3.2.6 on 2021-08-11 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='Calle')),
                ('number', models.IntegerField(verbose_name='Número')),
                ('postalCode', models.IntegerField(verbose_name='Código postal')),
                ('city', models.CharField(max_length=255, verbose_name='Ciudad')),
                ('province', models.CharField(max_length=255, verbose_name='Provincia')),
                ('reference', models.TextField(verbose_name='Referencia')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('email', models.CharField(max_length=255)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shopCart.address', verbose_name='Dirección')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.FloatField(verbose_name='Sub total')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopCart.user', verbose_name='Usuario')),
            ],
        ),
    ]
