# Generated by Django 3.2.6 on 2021-08-11 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210811_0003'),
        ('shopCart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDetailState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Estado de detalle de carro',
                'verbose_name_plural': 'Estados de detalle de carro',
            },
        ),
        migrations.CreateModel(
            name='ShopState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Estado de carro',
                'verbose_name_plural': 'Estados de carro',
            },
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Dirección', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterModelOptions(
            name='shopcart',
            options={'verbose_name': 'Carro de compras', 'verbose_name_plural': 'Carros de compras'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.CreateModel(
            name='ShopCartDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Cantidad')),
                ('subtotal', models.FloatField(verbose_name='Sub total')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product', verbose_name='Producto')),
                ('shopcart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopCart.shopcart', verbose_name='Carro de compras')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shopCart.shopdetailstate', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Detalle de Carro de compras',
                'verbose_name_plural': 'Detalle de Carro de compras',
            },
        ),
        migrations.AddField(
            model_name='shopcart',
            name='state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='shopCart.shopstate', verbose_name='Estado'),
        ),
    ]
