# Generated by Django 3.2.6 on 2021-08-24 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_sale_address'),
        ('shopCart', '0003_auto_20210824_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
