# Generated by Django 3.2.6 on 2021-08-29 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.FloatField(verbose_name='Sub total')),
            ],
            options={
                'verbose_name': 'Carro de compras',
                'verbose_name_plural': 'Carros de compras',
            },
        ),
        migrations.CreateModel(
            name='ShopDetailState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Estado de detalle de carro',
                'verbose_name_plural': 'Estados de detalle de carro',
            },
        ),
        migrations.CreateModel(
            name='ShopState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Estado de carro',
                'verbose_name_plural': 'Estados de carro',
            },
        ),
        migrations.CreateModel(
            name='ShopCartDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Cantidad')),
                ('subtotal', models.FloatField(verbose_name='Sub total')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product', verbose_name='Producto')),
                ('shopcart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_cart.shopcart', verbose_name='Carro de compras')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop_cart.shopdetailstate', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Detalle de Carro de compras',
                'verbose_name_plural': 'Detalle de Carro de compras',
            },
        ),
        migrations.AddField(
            model_name='shopcart',
            name='state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='shop_cart.shopstate', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='shopcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
