# Generated by Django 3.2.6 on 2021-08-30 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0002_alter_shopcart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcartdetail',
            name='shopcart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='shop_cart.shopcart', verbose_name='Carro de compras'),
        ),
    ]
