# Generated by Django 3.2.6 on 2021-09-07 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0003_alter_shopcartdetail_shopcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='state',
        ),
        migrations.AlterField(
            model_name='shopcartdetail',
            name='shopcart',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='shop_cart.shopcart', verbose_name='Carro de compras'),
        ),
        migrations.AlterField(
            model_name='shopcartdetail',
            name='state',
            field=models.SmallIntegerField(choices=[(1, 'En carro'), (2, 'Vendido'), (3, 'Cancelado')], default=1, verbose_name='Estado'),
        ),
        migrations.DeleteModel(
            name='ShopDetailState',
        ),
        migrations.DeleteModel(
            name='ShopState',
        ),
    ]
