# Generated by Django 3.2.6 on 2021-09-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0004_auto_20210907_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcartdetail',
            name='subtotal',
            field=models.FloatField(default=0, verbose_name='Sub total'),
        ),
    ]
