# Generated by Django 3.2.6 on 2021-09-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0005_alter_shopcartdetail_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='subtotal',
            field=models.FloatField(default=0, verbose_name='Sub total'),
        ),
    ]
