# Generated by Django 3.2.6 on 2021-09-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0006_alter_shopcart_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcartdetail',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Cantidad'),
        ),
    ]
