# Generated by Django 3.2.6 on 2021-08-28 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='total',
            field=models.FloatField(default=0, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='stocks.stock', verbose_name='Stock'),
        ),
    ]
