@startuml Class Diagram

class CategoriaProducto{
    - idCategoria: int
    - nombreCategoria: string
    - categoriaPadre: CategoriaProducto
    - cantidad: int


    + Categoria()
    + setID(int)
    + setNombre(String)
    + setCantidad(int)
    + agregarProducto(Producto producto)
    + getID(): int
    + getNombre(): String
    + getCantidad(): int
    + getProductos(): List<Productos>

}

class Proveedor{
    - idProveedor: int
    - nombreProveedor: string

    + Proveedor(int id, String nombre)
    + setID(int)
    + setNombreEntidad(Sting)
    + getID(): int
    + getNombreEntidad(): String


}

class Producto{
    - idProducto: int
    - nombreProducto: string
    - categoria: CategoriaProducto
    - proveedor: Proveedor
    - precio_unitaro: float
    - unidades_bulto : float
    - costo_bulto: float
    - activo: bool

    + Producto()
    + setID(int)
    + setNombre(String)
    + setStock(int)
    + setPrecio(float)
    + getID(): int
    + getNombre(): String
    + getSock(): int
    + getPrecio(): float
    + getCategoria(): Categoria
    + getProveedor(): Proveedor
}

class CarroCompras{
    - idCarro: int
    - estado:  string
    - usuario: Usuario
    - subtotal: float

    + Carrito()
    + setID(int)
    + getUsuario(): Usuario
    + getDetalle(): Detalle
    + MostrarCarrito(DetalleCarrito)
    + generarVenta(): Venta

}

class Usuario{
    - idUsuario: int
    - nombreUsuario: string
    - mailUsuario: string
    - direccion: Direccion

    + Usuario()
    + setID(int)
    + setNombreUsuario(String)
    + setCorreo(String)
    + getID(): int
    + getNombreUsuario(): String
    + getCorreo(): String
    + agregarDireccion(Direccion direccion)
    + getDirecciones(): List<Direccion>

}
class Direccion{
    - provincia: String
    - ciudad: String
    - codigoPostal: int
    - calle: String
    - numero: int
    - referencia: TextArea

    + Direccion()
    + setProvincia(String)
    + setCiudad(String)
    + setCP(int)
    + setCalle(String)
    + setNumero(int)
    + setReferencia(TextArea)
    + getProvincia():String
    + getCiudad(): String
    + getCP(): int
    + getCalle(): String
    + getNumero():int
    + getReferencia(): TextArea


}

class DetalleVenta{
    - id : int
    - producto : Producto
    - cantidad: int
    - subtotal: float
    - venta: Venta
    - detalleCarro: DetalleCarro

    + DetalleCarrito()
    + setCantidad(int)
    + setSubtotal(float)
}

class DetalleCarro{
    - id : int
    - producto : Producto
    - cantidad: int
    - subtotal: float
    - carro: CarroCompras

    + DetalleCarrito()
    + setCantidad(int)
    + setSubtotal(float)
    + migrarAVenta(Venta): DetalleVenta
}

class StockProducto{
    - proveedor: Proveedor
    - costo_total: float
    - fecha : Date
}

class DetalleStock{
    - stock: StockProducto
    - producto: Producto
    - cantidad: float
}

class Venta{
    - idVenta: int
    - detalleVenta: List<Detalle>
    - formaPago: int
    - totalVenta: float
    - comprador: Usuario
    - direccion: Direccion
    - costoEnvio: float

    + actualizarStock()
    + Venta()
    + setCostoEnvio(float)
    + calcularTotal(float)
    + getUsuario(): Usuario
    + getDetalle(): Detalle
    + getDireccion(): Direccion
}

StockProducto "0-n" --left--* "1" Proveedor
CategoriaProducto --> "1" CategoriaProducto
Producto "0-n" -up-> "1" CategoriaProducto
Producto "0-n" -up-> "1" Proveedor
CarroCompras "1" --> "0-n" DetalleCarro
Usuario "1" --* "1" CarroCompras
Usuario "1" <-- "0-n" Venta
Usuario "1-n" -right-> "1-n" Direccion
DetalleVenta "1" -up-> "1" Producto
DetalleCarro "1" -left-> "1" Producto
Venta "1" --o "1-n" DetalleVenta
Direccion "1" --> Venta
StockProducto "1" -down-> "0-n" DetalleStock
DetalleStock "1" -down-> "1" Producto
DetalleCarro "1" <-down- "1" DetalleVenta

@enduml