# Generated by Django 3.2.6 on 2021-09-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210830_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_per_package',
            field=models.IntegerField(default=1, verbose_name='Unidades por bulto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.FloatField(default=0, verbose_name='Precio Unitario'),
        ),
    ]
