# Generated by Django 3.2.6 on 2021-08-11 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopCart', '0002_auto_20210811_1401'),
        ('products', '0003_auto_20210811_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.FloatField(verbose_name='Sub total')),
                ('delivery_cost', models.FloatField(verbose_name='Costo de envío')),
                ('total', models.FloatField(verbose_name='Total')),
                ('address', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='shopCart.address', verbose_name='Dirección')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopCart.user', verbose_name='Cliente')),
                ('pay_method', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='sales.paymethod', verbose_name='Forma de pago')),
            ],
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Cantidad')),
                ('subtotal', models.FloatField(verbose_name='Sub total')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product', verbose_name='Producto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sale', verbose_name='Venta')),
                ('shop_cart_detail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shopCart.shopcartdetail', verbose_name='Detalle de carro')),
            ],
        ),
    ]
