# Generated by Django 3.2.6 on 2021-08-24 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='address',
        ),
    ]
